spring:
  application:
    name: moau

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}/${RDS_DB}
    username: ${RDS_USER}
    password: ${RDS_PASS}

  security:
    jwt:
      secret: ${SPRING_SECURITY_JWT_SECRET}
      access-token-expiration-msec: ${SPRING_SECURITY_JWT_ACCESSTOKENEXPIRATIONMSEC}
      refresh-token-expiration-msec: ${SPRING_SECURITY_JWT_REFRESHTOKENEXPIRATIONMSEC}

app:
  kakao:
    rest-api-key: ${APP_KAKAO_REST_API_KEY}
    token-uri: ${APP_KAKAO_TOKEN_URI}
    user-me-uri: ${APP_KAKAO_USER_ME_URI}
    redirect-uris:
      - ${APP_KAKAO_REDIRECT_URIS_0}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    doc-expansion: none
    default-models-expand-depth: -1
    tags-sorter: alpha